#ingress-controller
controller:
  service:
    type: NodePort
  hostPort:
    enabled: true
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"